spring.application.name=demo
spring.datasource.url=jdbc:postgresql://10.13.132.41:5434/demodac
spring.datasource.username=dacuser
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml